/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleDetailDialog: typeof import('./src/components/Dialog/Article/ArticleDetailDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfirmDialog: typeof import('./src/components/Dialog/ConfirmDialog.vue')['default']
    CreateArticleDialog: typeof import('./src/components/Dialog/Article/CreateArticleDialog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpdateArticleDialog: typeof import('./src/components/Dialog/Article/UpdateArticleDialog.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
  }
}
